install.packages("devtools")
# ###### If needed
library(devtools)
install_github("ccrismancox/games2")
# #####
install_version("doParallel", "1.0.16")
install_version("doRNG", "1.8.2")
install_version("brglm", "0.7.2")
install_version("detectseparation", "0.2")
install_version("matrixStats", "0.60.1")
install_version("Formula", "1.2-4")
install_version("knitr", "1.33")
install_version("numDeriv", "2016.8-1.1")
install_version("readstata13", "0.10.0")
install_version("ggplot2", "3.3.6")
install_version("gridExtra", "2.3")
install_version("stringr", "1.4.0")
install_version("mc2d", "0.1-21")


library(games2)
library(doRNG)
library(brglm)
library(detectseparation)
library(matrixStats)
library(Formula)
library(knitr)
library(numDeriv)
library(readstata13)
library(ggplot2)
library(gridExtra)
library(stringr)
library(mc2d)
